### PR TITLE
[#79] Prevent generating SSL files when enable_ssl is false

### PR DESCRIPTION
**Pull request by alanking**
Not fully tested, mostly PR'ing for visibility.

### CODE REVIEW

**Comment by jassigill2000** [comment]
the changes so far seem like they won't break anything.

**Comment by alanking** [comment]
This change also generates the SSL files once on the catalog provider and copies the files to a known location in the catalog consumer containers. Before, the SSL files would be generated for each machine and copied each time.

**Comment by trel** [comment]
seems good - # and ship it if it's working

**Comment by alanking** [comment]
It seems that the run_tests_on_topology job never ends (and never cleans up the containers/network) so I'm going to try to get that fixed up first.

**Comment by alanking** [comment]
Things are working now. #'s added. Stating again here for posterity: The changes to address #82 are to clear the way for SSL testing for the consortium, but it is a workaround.

**Pull request merged**
